### PR TITLE
Stores backgrounds in the client

### PR DESCRIPTION
**Pull request by ctrlraul**
My first time stepping here so tried something simple to get started

1. Stores the background images in the client
2. Implements singleton `BackgroundsLoader` which dynamically loads a list of all backgrounds stored locally, so no need to hardcode background ids

Can be modified to also load backgrounds from the web.

This solves the slow loading of background images in the editor and potentially unwanted network usage in the long term.

### CODE REVIEW

**Comment by jacob-grahn** [comment]
Thanks ctrlraul, I'd rather not store the backgrounds in the client for a couple of reasons:
1. Adding / changing backgrounds without releasing a new build. Releasing a new build will become bothersome once the game is on steam/ios/android/web/etc
2. Support user created backgrounds in the future

It would be nice to load backgrounds from the web and then store them locally. Then future requests for the background would be faster. Similar to the music player: https://github.com/jacob-grahn/platform-racing-4/blob/main/client/singletons/jukebox/Jukebox.gd

**Comment by ctrlraul** [comment]
Understood.

That is my plan B indeed, I'll push to this soon.

**Comment by ctrlraul** [comment]
> 2\. Support user created backgrounds in the future

Almost done but how do you plan for this to work?

**Comment by jacob-grahn** [comment]
It could still work the same for user uploaded backgrounds, just the background id might look something like `user-id/bg-id`

**Comment by ctrlraul** [comment]
Loads all default backgrounds on start, if they don't exist in the cache, downloads and stores them to cache for future sessions. Trying to get an user-made background will follow the same process, but only the default backgrounds are automatically loaded on start.

Assumes all backgrounds are jpg at the moment.

**Comment by ctrlraul** [comment]
Might still wanna visit this to handle cache purging but figured I'd push at this point.

**Comment by jacob-grahn** [comment]
Thanks ctrlraul!

**Pull request merged**
