### PR TITLE
Added a basic text placer in the editor

### PR DESCRIPTION
**Pull request by CamerTheDragon**
It says: "Default Text!" in the font used for the buttons. Text is not editable at this current time.

### CODE REVIEW

**Comment by jacob-grahn** [comment]
I think we should leave this one on a branch until the text is editable

**Comment by CamerTheDragon** [comment]
Sounds good, I shall work on making the text editable next

**Comment by CamerTheDragon** [comment]
Text is technically editable now but I'll reclose this for the time being as it is a little wonky in implementation:
- Creating/Editing will need some work as now it's randomised which it'll be when selecting the tab
- Text can be dragged on placing but not after
- Text can be messed when testing the level
- Textbox cannot be deleted (text can, but not the underlying textbox)

**Comment by CamerTheDragon** [comment]
Some improvements have been made so I will reopen this for feedback
- Creating/Editing Text is now more logical: on "Add Text", the initial click will place text (it always will though) and any subsequent ones won't place text but will instead let you edit existing text.
- Text should no longer able to be selected/highlighted in testing a level in the editor.
- The context menu should no longer show on menu-click (typically right-click)

Here is something that may be a positive or a negative depending:
- If the text is too long, it will scroll in the box. You can scroll the box to see all of the text both in editor and when playing. This allows for more compact text, but may not be desired due to the scrolling during gameplay. The scroll bar only appears on text that exceeds the size of the TextEdit box.

Here are what I would say the next things for the text would be:
- Allow for moving (after initial placing), deleting, and resizing of the text boxes.

**Comment by jacob-grahn** [comment]
Wow, fast work!

**Pull request merged**
